before_script:
  - apt-get install nasm
  - rustup component add rust-src

workflow:
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "redox-os"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

stages:
  - host

build:i586:
  stage: host
  script:
    - TARGET=x86-unknown-none make all

build:x86_64:
  stage: host
  script:
    - TARGET=x86_64-unknown-uefi make all

build:aarch64:
  stage: host
  script:
    - TARGET=aarch64-unknown-uefi make all

fmt:
  stage: host
  script:
      - rustup component add rustfmt-preview
      - cargo fmt -- --check
